# Generated by Django 3.0.1 on 2020-01-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary', models.IntegerField()),
                ('summary', models.TextField()),
                ('Featured', models.BooleanField()),
            ],
        ),
    ]
