# Generated by Django 3.0.1 on 2020-01-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherprofile', '0002_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='title',
        ),
        migrations.AddField(
            model_name='prof',
            name='course',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prof',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
