# Generated by Django 3.0.2 on 2020-02-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutor',
            new_name='Tutors',
        ),
    ]
