# Generated by Django 3.0.2 on 2020-02-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutor_profile',
        ),
    ]
